version: "3.8"
services:
  php-fpm:
    image: php-fpm
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/usuario/cacti/:/var/www/html/cacti/
      - /home/usuario/php-nginx/bind.conf:/etc/php/8.2/fpm/pool.d/bind.conf
      - /home/usuario/php-nginx/99-override-php.ini:/etc/php/8.2/fpm/conf.d/99-override-php.ini
    networks:
      - cacti

  nginx:
    depends_on:
      - php-fpm
    image: nginx
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/usuario/php-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/usuario/php-nginx/cacti.conf:/etc/nginx/conf.d/cacti.conf
      - /home/usuario/cacti/:/var/www/html/cacti/
    networks:
      - cacti

  db:
    container_name: mysql_bd_cacti
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - /home/usuario/mysql/data:/var/lib/mysql
      - /home/usuario/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - cacti

networks:
  cacti:
    external: true
