version: "3.8"
services:
    freeipa-almalinux9:
        tty: true
        stdin_open: true
        restart: unless-stopped
        hostname: cacti.ufrj.br
        ports:
            - 81:80
            - 443:443
            - 389:389
            - 636:636
            - 88:88
            - 464:464
            - 88:88/udp
            - 464:464/udp
            - 123:123/udp
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - <volume para persistência>/data:/data:Z
        image: freeipa-almalinux9
